//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIngredient()
        {
            this.tblShoppingLists = new HashSet<tblShoppingList>();
        }
    
        public int ingridientId { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public Nullable<int> recipeId { get; set; }
    
        public virtual tblRecipe tblRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShoppingList> tblShoppingLists { get; set; }
    }
}
