//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShoppingList
    {
        public int shoppingListId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> ingridientId { get; set; }
        public bool @checked { get; set; }
    
        public virtual tblIngredient tblIngredient { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
