//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRecipe
    {
        public int recipeId { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public int numberOfPersons { get; set; }
        public string description { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<int> authorId { get; set; }
        public string fullname { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public string username { get; set; }
    }
}
